# Generated by Django 4.2.7 on 2025-10-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('grade_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='speech_samples/')),
                ('text_content', models.TextField(help_text='The text that was spoken')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_preprocessed', models.BooleanField(default=False)),
                ('preprocessed_audio', models.FileField(blank=True, null=True, upload_to='preprocessed_speech/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HandwritingSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='handwriting_samples/')),
                ('text_content', models.TextField(help_text='The text that was written')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('eye_tracking_data', models.JSONField(blank=True, help_text='Eye tracking coordinates', null=True)),
                ('is_preprocessed', models.BooleanField(default=False)),
                ('preprocessed_image', models.ImageField(blank=True, null=True, upload_to='preprocessed_handwriting/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EyeTrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('pupil_diameter', models.FloatField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_tracking', to='data_collection.handwritingsample')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
