# Generated by Django 5.2.10 on 2026-02-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_videosample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
