# Generated by Django 4.2.7 on 2025-10-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwritingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('model_file', models.FileField(upload_to='handwriting_models/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandwritingAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('irregular_shapes_score', models.FloatField(help_text='Score for irregular letter shapes (0-1)')),
                ('spacing_issues_score', models.FloatField(help_text='Score for spacing problems (0-1)')),
                ('stroke_pattern_score', models.FloatField(help_text='Score for stroke pattern irregularities (0-1)')),
                ('overall_handwriting_score', models.FloatField(help_text='Overall handwriting quality score (0-1)')),
                ('letter_formation_issues', models.JSONField(default=list, help_text='List of specific letter formation problems')),
                ('spacing_analysis', models.JSONField(default=dict, help_text='Detailed spacing analysis')),
                ('stroke_analysis', models.JSONField(default=dict, help_text='Detailed stroke pattern analysis')),
                ('model_confidence', models.FloatField(help_text='CNN model confidence in analysis (0-1)')),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.handwritingsample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
