# Generated by Django 4.2.7 on 2025-10-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speech_analysis', '0001_initial'),
        ('handwriting_analysis', '0001_initial'),
        ('data_collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('model_file', models.FileField(upload_to='detection_models/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dyslexia_probability', models.FloatField(help_text='Probability of dyslexia (0-1)')),
                ('dysgraphia_probability', models.FloatField(help_text='Probability of dysgraphia (0-1)')),
                ('overall_risk_score', models.FloatField(help_text='Overall risk score (0-1)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('detection_confidence', models.FloatField(help_text='Overall detection confidence (0-1)')),
                ('recommended_actions', models.JSONField(default=list, help_text='List of recommended actions')),
                ('strengths_identified', models.JSONField(default=list, help_text='List of identified strengths')),
                ('areas_of_concern', models.JSONField(default=list, help_text='List of areas requiring attention')),
                ('detection_timestamp', models.DateTimeField(auto_now_add=True)),
                ('handwriting_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handwriting_analysis.handwritinganalysis')),
                ('handwriting_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_collection.handwritingsample')),
                ('speech_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speech_analysis.speechanalysis')),
                ('speech_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_collection.speechsample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
