# Generated by Django 5.2.10 on 2026-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('high', 'High Risk')], max_length=10),
        ),
    ]
