# Generated by Django 4.2.7 on 2025-10-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('model_file', models.FileField(upload_to='speech_models/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pronunciation_score', models.FloatField(help_text='Pronunciation accuracy score (0-1)')),
                ('fluency_score', models.FloatField(help_text='Speech fluency score (0-1)')),
                ('reading_speed', models.FloatField(help_text='Words per minute')),
                ('pause_frequency', models.FloatField(help_text='Number of pauses per minute')),
                ('mispronunciations', models.JSONField(default=list, help_text='List of mispronounced words')),
                ('fluency_issues', models.JSONField(default=list, help_text='List of fluency problems')),
                ('phoneme_analysis', models.JSONField(default=dict, help_text='Phoneme-level analysis')),
                ('pitch_variation', models.FloatField(help_text='Pitch variation score')),
                ('volume_consistency', models.FloatField(help_text='Volume consistency score')),
                ('rhythm_score', models.FloatField(help_text='Speech rhythm score')),
                ('model_confidence', models.FloatField(help_text='Model confidence in analysis (0-1)')),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.speechsample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
